[font]
size = 14.0

[font.normal]
family = "Menlo"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
option_as_alt = "Both"

# The following fixes ctrl-/ on macOS with Alacritty, but we can alternatively use ctrl-_ or ctrl--:
# [keyboard]
# bindings = [
#   { key = "Slash", mods = "Control", chars = "\u001f" }
# ]

